name = "backend1"
# This backend wants to work with floats, but explicitly also supports ints.
# By default it will not be used (int is the default primary type). But it
# can be prioritized or could use `prioritize_above = ["default"]`.
primary_types = ["builtins:float", "builtins:int"]
secondary_types = []
requires_opt_in = False


# BEGIN AUTOGENERATED CODE: functions
functions = {
    "spatch._spatch_example.library:divide": {
        "function": "spatch._spatch_example.backend:divide",
        "should_run": "spatch._spatch_example.backend:divide._should_run",
        "uses_context": True,
        "additional_docs": "This implementation works well on floats.",
    }
}
# END AUTOGENERATED CODE: functions

# TODO: The documentation has to tell people not to create circles.
# and that includes with the types?!
# prioritize_above = ["default"]

if __name__ == "__main__":
    # Run this file as a script to update this file
    from spatch.backend_utils import update_entrypoint
    from spatch._spatch_example.backend import backend1

    update_entrypoint(__file__, backend1, "spatch._spatch_example.backend")
